on:
  workflow_call:
    inputs:
      command:
        required: true
        type: string
      gcloudProject:
        required: true
        type: string
    secrets:
      DISCORD_API_KEY:
        required: true
      DISCORD_PUBLIC_KEY:
        required: true
      DISCORD_APPLICATION_ID:
        required: true


jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0.7.1'
        with:
          workload_identity_provider: 'projects/${{ inputs.gcloudProject }}/locations/global/workloadIdentityPools/cicd/providers/github-actions'
          service_account: 'github-actions-${{ inputs.command }}@${{ inputs.gcloudProject }}.iam.gserviceaccount.com'
      - name: terraform ${{ inputs.command }}
        run: yes | terraform ${{ inputs.command }}
        env:
          TF_VAR_discord_apikey: ${{ secrets.DISCORD_API_KEY }}
          TF_VAR_discord_public_key: ${{ secrets.DISCORD_PUBLIC_KEY }}
          TF_VAR_discord_application_id: ${{ secrets.DISCORD_APPLICATION_ID }}
          TF_VAR_github_repository: ${{ github.repository }}
