name: terraform plan
on:
  pull_request:
permissions:
  contents: read
  id-token: write
jobs:
  plan:
    uses: ./.github/workflows/terraform.yml
    with:
      command: plan
      gcloudProject: "t98s-mc-testbed"
    secrets:
      DISCORD_API_KEY: dummy
      DISCORD_PUBLIC_KEY: dummy
      DISCORD_APPLICATION_ID: dummy
