name: terraform apply
on:
  push:
    branches: ["main"]
permissions:
  contents: read
  id-token: write
jobs:
  plan:
    uses: ./.github/workflows/terraform.yml
    with:
      command: apply
      gcloudProject: "t98s-mc-testbed"
    secrets:
      DISCORD_API_KEY: ${{ secrets.DISCORD_API_KEY }}
      DISCORD_PUBLIC_KEY: ${{ secrets.DISCORD_PUBLIC_KEY }}
      DISCORD_APPLICATION_ID: ${{ secrets.DISCORD_APPLICATION_ID }}
