name: terraform plan
on:
  pull_request:

permissions:
  contents: read
  id-token: write
  pull-requests: write
jobs:
  plan:
    if: github.event.pull_request.head.repo.id == github.event.pull_request.base.repo.id
    uses: ./.github/workflows/terraform.yml
    with:
      command: plan
      tfcmt: true
    secrets:
      GCLOUD_PROJECT: ${{ secrets.GCLOUD_PROJECT }}
      GCLOUD_PROJECT_ID: ${{ secrets.GCLOUD_PROJECT_ID }}
      DISCORD_API_KEY: ${{ secrets.DISCORD_API_KEY }}
      DISCORD_PUBLIC_KEY: ${{ secrets.DISCORD_PUBLIC_KEY }}
      DISCORD_APPLICATION_ID: ${{ secrets.DISCORD_APPLICATION_ID }}
