name: terraform plan
on:
  # fork でも origin の context で実行されるようにする
  # 当然 unsafe であるので、権限を持つ人が review_request を行なったときに自動で走るという整理にする
  # https://securitylab.github.com/research/github-actions-preventing-pwn-requests/
  pull_request_target:
    types: [review_requested]
permissions:
  contents: read
  id-token: write
jobs:
  plan:
    uses: ./.github/workflows/terraform.yml
    with:
      command: plan
      ref: "refs/pull/${{ github.event.number }}/merge"
    secrets:
      GCLOUD_PROJECT: ${{ secrets.GCLOUD_PROJECT }}
      DISCORD_API_KEY: dummy
      DISCORD_PUBLIC_KEY: dummy
      DISCORD_APPLICATION_ID: dummy
